# Generated by Django 3.0.7 on 2020-06-18 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_branch', models.CharField(max_length=50, verbose_name='الشعبة')),
                ('point', models.CharField(max_length=50, verbose_name='')),
                ('nation_num', models.IntegerField(verbose_name='')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('father_name', models.CharField(max_length=50, verbose_name='')),
                ('mother_name', models.CharField(max_length=50, verbose_name='')),
                ('type_of_person', models.CharField(max_length=50, verbose_name='')),
                ('birth_place', models.CharField(max_length=50, verbose_name='')),
                ('brith_date', models.DateField(verbose_name='')),
                ('social_status', models.CharField(max_length=50, verbose_name='')),
                ('mobile', models.IntegerField(verbose_name='')),
                ('phone', models.IntegerField(verbose_name='')),
                ('education', models.CharField(max_length=50, verbose_name='')),
                ('education_detail', models.TextField(verbose_name='')),
                ('sarc_adjective', models.CharField(max_length=50, verbose_name='')),
                ('position', models.CharField(max_length=50, verbose_name='')),
                ('volunteer_date', models.DateField(verbose_name='')),
                ('employment_date', models.DateField(verbose_name='')),
                ('blood_type', models.CharField(max_length=50, verbose_name='')),
                ('name_e', models.CharField(max_length=50, verbose_name='')),
                ('position_e', models.CharField(max_length=50, verbose_name='')),
                ('shoce_size', models.IntegerField(verbose_name='')),
                ('waist_size', models.IntegerField(verbose_name='')),
                ('shoulder_size', models.CharField(max_length=50, verbose_name='')),
                ('rank_in_team', models.CharField(max_length=50, verbose_name='')),
                ('advanced_date', models.DateField(verbose_name='')),
                ('training_postion', models.CharField(max_length=50, verbose_name='')),
                ('tot_date', models.DateField(verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
