# Generated by Django 3.0.7 on 2020-06-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='advanced_date',
            field=models.DateField(verbose_name='تاريخ دورة المتقدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_place',
            field=models.CharField(max_length=50, verbose_name='مكان الولادة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(max_length=50, verbose_name='زمرة الدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brith_date',
            field=models.DateField(verbose_name='تاريخ الولادة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(max_length=50, verbose_name='الشهادة العلمية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_detail',
            field=models.TextField(verbose_name='تفاصيل التحيل العلمي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_date',
            field=models.DateField(verbose_name='تاريخ التوظيف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='اسم الأب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(verbose_name='موبايل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(max_length=50, verbose_name='اسم الأم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_e',
            field=models.CharField(max_length=50, verbose_name='الاسم بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nation_num',
            field=models.IntegerField(verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(verbose_name='هاتف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.CharField(max_length=50, verbose_name='النقطة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=50, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(max_length=50, verbose_name='المنصب بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank_in_team',
            field=models.CharField(max_length=50, verbose_name='الرتبة ضمن الفريق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sarc_adjective',
            field=models.CharField(max_length=50, verbose_name='الصفة الهلالية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoce_size',
            field=models.IntegerField(verbose_name='قياس الحذاء'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_size',
            field=models.CharField(max_length=50, verbose_name='قياس الكتفين'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_status',
            field=models.CharField(max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tot_date',
            field=models.DateField(verbose_name='تاريخ دورة تي او تي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_postion',
            field=models.CharField(max_length=50, verbose_name='الصفة بالتدريب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(max_length=50, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='volunteer_date',
            field=models.DateField(verbose_name='تاريخ التطوع'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='waist_size',
            field=models.IntegerField(verbose_name='قياس الخصر'),
        ),
    ]
