# Generated by Django 3.0.7 on 2020-06-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.PositiveIntegerField(max_length=10, verbose_name='جوال'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(max_length=50, verbose_name='  الجنس'),
        ),
    ]
