# Generated by Django 3.0.7 on 2020-06-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200619_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(choices=[('A-', 'A-'), ('AB+', 'AB+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('O+', 'O+'), ('B-', 'B-'), ('B+', 'B+')], max_length=50, verbose_name='زمرة الدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('شهادة جامعية', 'شهادة جامعية'), ('دكتوراه', 'دكتوراه'), ('شهادة ابتدائية', 'شهادة ابتدائية'), ('دبلوم', 'دبلوم'), ('شهادة ثانوية', 'شهادة ثانوية'), ('معهد', 'معهد'), ('طالب جامعي', 'طالب جامعي'), ('شهادة إعدادية', 'شهادة إعدادية'), ('غير متعلم', 'غير متعلم'), ('ماجستير', 'ماجستير')], max_length=50, verbose_name='الشهادة العلمية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('مساعد منسق الإسعاف', 'مساعد منسق الإسعاف'), ('مستشار طبي', 'مستشار طبي'), ('لوجستي إسعاف', 'لوجستي إسعاف'), ('منسق عمليات الإسعاف', 'منسق عمليات الإسعاف'), ('منسق فريق الإسعاف', 'منسق فريق الإسعاف'), ('مسؤول مركز', 'مسؤول مركز'), ('سائق', 'سائق'), ('مستخدم', 'مستخدم'), ('منسق التدريب', 'منسق التدريب')], max_length=50, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(choices=[('Assistant Ambulance Coordinator', 'Assistant Ambulance Coordinator'), ('Training Coordinator', 'Training Coordinator'), ('user', 'user'), ('Driver', 'Driver'), ('Medical Advisor', 'Medical Advisor'), ('Ambulance Operations Coordinator', 'Ambulance Operations Coordinator'), ('Ambulance Logistic', 'Ambulance Logistic'), ('Center Official', 'Center Official'), ('Ambulance Team Coordinator', 'Ambulance Team Coordinator')], max_length=50, verbose_name='المنصب بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank_in_team',
            field=models.CharField(choices=[('قائد فريق', 'قائد فريق'), ('قائد قطاع', 'قائد قطاع'), ('قائد قطاع تحت التدريب', 'قائد قطاع تحت التدريب'), ('مسعف تحت التدريب', 'مسعف تحت التدريب'), ('مسعف', 'مسعف'), ('كشاف', 'كشاف')], max_length=50, verbose_name='الرتبة ضمن الفريق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sarc_adjective',
            field=models.CharField(choices=[('متطوع', 'متطوع'), ('موظف', 'موظف')], max_length=50, verbose_name='الصفة الهلالية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_size',
            field=models.CharField(choices=[('M', 'M'), ('XXL', 'XXL'), ('S', 'S'), ('L', 'L'), ('XL', 'XL')], max_length=50, verbose_name='قياس الكتفين'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_status',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('أعزب', 'أعزب')], max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_postion',
            field=models.CharField(choices=[('مساعد مدرب', 'مساعد مدرب'), ('مدرب', 'مدرب')], max_length=50, verbose_name='الصفة بالتدريب'),
        ),
    ]
