# Generated by Django 3.0.7 on 2020-06-19 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200619_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(choices=[('B-', 'B-'), ('A-', 'A-'), ('AB+', 'AB+'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('AB-', 'AB-')], max_length=50, verbose_name='زمرة الدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('شهادة جامعية', 'شهادة جامعية'), ('شهادة ابتدائية', 'شهادة ابتدائية'), ('ماجستير', 'ماجستير'), ('طالب جامعي', 'طالب جامعي'), ('معهد', 'معهد'), ('شهادة ثانوية', 'شهادة ثانوية'), ('شهادة إعدادية', 'شهادة إعدادية'), ('دبلوم', 'دبلوم'), ('غير متعلم', 'غير متعلم'), ('دكتوراه', 'دكتوراه')], max_length=50, verbose_name='الشهادة العلمية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(verbose_name='جوال'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nation_num',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('[0-9]')], verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('لوجستي إسعاف', 'لوجستي إسعاف'), ('منسق التدريب', 'منسق التدريب'), ('مستشار طبي', 'مستشار طبي'), ('مساعد منسق الإسعاف', 'مساعد منسق الإسعاف'), ('سائق', 'سائق'), ('منسق فريق الإسعاف', 'منسق فريق الإسعاف'), ('مسؤول مركز', 'مسؤول مركز'), ('مستخدم', 'مستخدم'), ('منسق عمليات الإسعاف', 'منسق عمليات الإسعاف')], max_length=50, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(choices=[('Ambulance Team Coordinator', 'Ambulance Team Coordinator'), ('user', 'user'), ('Ambulance Operations Coordinator', 'Ambulance Operations Coordinator'), ('Training Coordinator', 'Training Coordinator'), ('Ambulance Logistic', 'Ambulance Logistic'), ('Medical Advisor', 'Medical Advisor'), ('Center Official', 'Center Official'), ('Driver', 'Driver'), ('Assistant Ambulance Coordinator', 'Assistant Ambulance Coordinator')], max_length=50, verbose_name='المنصب بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank_in_team',
            field=models.CharField(choices=[('قائد قطاع', 'قائد قطاع'), ('كشاف', 'كشاف'), ('مسعف', 'مسعف'), ('قائد قطاع تحت التدريب', 'قائد قطاع تحت التدريب'), ('مسعف تحت التدريب', 'مسعف تحت التدريب'), ('قائد فريق', 'قائد فريق')], max_length=50, verbose_name='الرتبة ضمن الفريق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_size',
            field=models.CharField(choices=[('M', 'M'), ('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('S', 'S')], max_length=50, verbose_name='قياس الكتفين'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_status',
            field=models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_branch',
            field=models.CharField(choices=[('شعبة السلمية', 'شعبة السلمية'), ('فرع حماة', 'فرع حماة'), ('شعبة السقيلبية', 'شعبة السقيلبية'), ('شعبة مصياف', 'شعبة مصياف')], max_length=50, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_postion',
            field=models.CharField(choices=[('مدرب', 'مدرب'), ('مساعد مدرب', 'مساعد مدرب')], max_length=50, verbose_name='الصفة بالتدريب'),
        ),
    ]
