# Generated by Django 3.0.7 on 2020-06-19 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200619_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(choices=[('AB+', 'AB+'), ('O-', 'O-'), ('B-', 'B-'), ('O+', 'O+'), ('A+', 'A+'), ('AB-', 'AB-'), ('A-', 'A-'), ('B+', 'B+')], max_length=50, verbose_name='زمرة الدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('ماجستير', 'ماجستير'), ('شهادة ثانوية', 'شهادة ثانوية'), ('شهادة ابتدائية', 'شهادة ابتدائية'), ('طالب جامعي', 'طالب جامعي'), ('معهد', 'معهد'), ('شهادة إعدادية', 'شهادة إعدادية'), ('شهادة جامعية', 'شهادة جامعية'), ('دبلوم', 'دبلوم'), ('دكتوراه', 'دكتوراه'), ('غير متعلم', 'غير متعلم')], max_length=50, verbose_name='الشهادة العلمية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9].{9}$')], verbose_name='جوال'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nation_num',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('[0-9].{10}$')], verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9].{9}$')], verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('مستخدم', 'مستخدم'), ('منسق التدريب', 'منسق التدريب'), ('سائق', 'سائق'), ('مساعد منسق الإسعاف', 'مساعد منسق الإسعاف'), ('لوجستي إسعاف', 'لوجستي إسعاف'), ('مسؤول مركز', 'مسؤول مركز'), ('منسق فريق الإسعاف', 'منسق فريق الإسعاف'), ('منسق عمليات الإسعاف', 'منسق عمليات الإسعاف'), ('مستشار طبي', 'مستشار طبي')], max_length=50, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(choices=[('user', 'user'), ('Ambulance Logistic', 'Ambulance Logistic'), ('Ambulance Team Coordinator', 'Ambulance Team Coordinator'), ('Center Official', 'Center Official'), ('Assistant Ambulance Coordinator', 'Assistant Ambulance Coordinator'), ('Driver', 'Driver'), ('Ambulance Operations Coordinator', 'Ambulance Operations Coordinator'), ('Training Coordinator', 'Training Coordinator'), ('Medical Advisor', 'Medical Advisor')], max_length=50, verbose_name='المنصب بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank_in_team',
            field=models.CharField(choices=[('قائد فريق', 'قائد فريق'), ('مسعف', 'مسعف'), ('قائد قطاع', 'قائد قطاع'), ('قائد قطاع تحت التدريب', 'قائد قطاع تحت التدريب'), ('مسعف تحت التدريب', 'مسعف تحت التدريب'), ('كشاف', 'كشاف')], max_length=50, verbose_name='الرتبة ضمن الفريق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_size',
            field=models.CharField(choices=[('XL', 'XL'), ('XXL', 'XXL'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=50, verbose_name='قياس الكتفين'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_status',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('أعزب', 'أعزب')], max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_branch',
            field=models.CharField(choices=[('شعبة السلمية', 'شعبة السلمية'), ('فرع حماة', 'فرع حماة'), ('شعبة مصياف', 'شعبة مصياف'), ('شعبة السقيلبية', 'شعبة السقيلبية')], max_length=50, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_postion',
            field=models.CharField(choices=[('مدرب', 'مدرب'), ('مساعد مدرب', 'مساعد مدرب')], max_length=50, verbose_name='الصفة بالتدريب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=50, verbose_name='  الجنس'),
        ),
    ]
