# Generated by Django 3.0.7 on 2020-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200619_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(choices=[('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50, verbose_name='زمرة الدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('طالب جامعي', 'طالب جامعي'), ('شهادة ابتدائية', 'شهادة ابتدائية'), ('شهادة إعدادية', 'شهادة إعدادية'), ('معهد', 'معهد'), ('شهادة جامعية', 'شهادة جامعية'), ('دبلوم', 'دبلوم'), ('غير متعلم', 'غير متعلم'), ('دكتوراه', 'دكتوراه'), ('ماجستير', 'ماجستير'), ('شهادة ثانوية', 'شهادة ثانوية')], max_length=50, verbose_name='الشهادة العلمية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('منسق عمليات الإسعاف', 'منسق عمليات الإسعاف'), ('سائق', 'سائق'), ('مستشار طبي', 'مستشار طبي'), ('مستخدم', 'مستخدم'), ('مساعد منسق الإسعاف', 'مساعد منسق الإسعاف'), ('مسؤول مركز', 'مسؤول مركز'), ('لوجستي إسعاف', 'لوجستي إسعاف'), ('منسق التدريب', 'منسق التدريب'), ('منسق فريق الإسعاف', 'منسق فريق الإسعاف')], max_length=50, null=True, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(blank=True, choices=[('Training Coordinator', 'Training Coordinator'), ('Center Official', 'Center Official'), ('user', 'user'), ('Ambulance Operations Coordinator', 'Ambulance Operations Coordinator'), ('Medical Advisor', 'Medical Advisor'), ('Assistant Ambulance Coordinator', 'Assistant Ambulance Coordinator'), ('Driver', 'Driver'), ('Ambulance Team Coordinator', 'Ambulance Team Coordinator'), ('Ambulance Logistic', 'Ambulance Logistic')], max_length=50, null=True, verbose_name='المنصب بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank_in_team',
            field=models.CharField(choices=[('مسعف', 'مسعف'), ('كشاف', 'كشاف'), ('قائد فريق', 'قائد فريق'), ('مسعف تحت التدريب', 'مسعف تحت التدريب'), ('قائد قطاع', 'قائد قطاع'), ('قائد قطاع تحت التدريب', 'قائد قطاع تحت التدريب')], max_length=50, verbose_name='الرتبة ضمن الفريق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_size',
            field=models.CharField(choices=[('S', 'S'), ('L', 'L'), ('XXL', 'XXL'), ('M', 'M'), ('XL', 'XL')], max_length=50, verbose_name='قياس الكتفين'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_branch',
            field=models.CharField(choices=[('فرع حماة', 'فرع حماة'), ('شعبة السلمية', 'شعبة السلمية'), ('شعبة السقيلبية', 'شعبة السقيلبية'), ('شعبة مصياف', 'شعبة مصياف')], max_length=50, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_postion',
            field=models.CharField(blank=True, choices=[('مساعد مدرب', 'مساعد مدرب'), ('مدرب', 'مدرب')], max_length=50, null=True, verbose_name='الصفة بالتدريب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=50, verbose_name='  الجنس'),
        ),
    ]
