# Generated by Django 3.0.7 on 2020-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200619_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50, verbose_name='زمرة الدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('شهادة ثانوية', 'شهادة ثانوية'), ('طالب جامعي', 'طالب جامعي'), ('دكتوراه', 'دكتوراه'), ('شهادة جامعية', 'شهادة جامعية'), ('ماجستير', 'ماجستير'), ('شهادة إعدادية', 'شهادة إعدادية'), ('غير متعلم', 'غير متعلم'), ('معهد', 'معهد'), ('شهادة ابتدائية', 'شهادة ابتدائية'), ('دبلوم', 'دبلوم')], max_length=50, verbose_name='الشهادة العلمية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('مسؤول مركز', 'مسؤول مركز'), ('مستشار طبي', 'مستشار طبي'), ('لوجستي إسعاف', 'لوجستي إسعاف'), ('منسق عمليات الإسعاف', 'منسق عمليات الإسعاف'), ('منسق التدريب', 'منسق التدريب'), ('مستخدم', 'مستخدم'), ('مساعد منسق الإسعاف', 'مساعد منسق الإسعاف'), ('منسق فريق الإسعاف', 'منسق فريق الإسعاف'), ('سائق', 'سائق')], max_length=50, null=True, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('Driver', 'Driver'), ('Ambulance Operations Coordinator', 'Ambulance Operations Coordinator'), ('Training Coordinator', 'Training Coordinator'), ('Ambulance Team Coordinator', 'Ambulance Team Coordinator'), ('Assistant Ambulance Coordinator', 'Assistant Ambulance Coordinator'), ('Ambulance Logistic', 'Ambulance Logistic'), ('Center Official', 'Center Official'), ('Medical Advisor', 'Medical Advisor')], max_length=50, null=True, verbose_name='المنصب بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank_in_team',
            field=models.CharField(choices=[('قائد قطاع', 'قائد قطاع'), ('مسعف تحت التدريب', 'مسعف تحت التدريب'), ('كشاف', 'كشاف'), ('قائد قطاع تحت التدريب', 'قائد قطاع تحت التدريب'), ('قائد فريق', 'قائد فريق'), ('مسعف', 'مسعف')], max_length=50, verbose_name='الرتبة ضمن الفريق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_size',
            field=models.CharField(choices=[('L', 'L'), ('S', 'S'), ('XL', 'XL'), ('M', 'M'), ('XXL', 'XXL')], max_length=50, verbose_name='قياس الكتفين'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_status',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('أعزب', 'أعزب')], max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_branch',
            field=models.CharField(choices=[('شعبة السقيلبية', 'شعبة السقيلبية'), ('فرع حماة', 'فرع حماة'), ('شعبة السلمية', 'شعبة السلمية'), ('شعبة مصياف', 'شعبة مصياف')], max_length=50, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_postion',
            field=models.CharField(blank=True, choices=[('مدرب', 'مدرب'), ('مساعد مدرب', 'مساعد مدرب')], max_length=50, null=True, verbose_name='الصفة بالتدريب'),
        ),
    ]
