# Generated by Django 3.0.7 on 2020-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200619_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('غير متعلم', 'غير متعلم'), ('شهادة ابتدائية', 'شهادة ابتدائية'), ('شهادة إعدادية', 'شهادة إعدادية'), ('شهادة ثانوية', 'شهادة ثانوية'), ('طالب جامعي', 'طالب جامعي'), ('معهد', 'معهد'), ('شهادة جامعية', 'شهادة جامعية'), ('دبلوم', 'دبلوم'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه')], max_length=50, verbose_name='الشهادة العلمية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('منسق فريق الإسعاف', 'منسق فريق الإسعاف'), ('مساعد منسق الإسعاف', 'مساعد منسق الإسعاف'), ('منسق عمليات الإسعاف', 'منسق عمليات الإسعاف'), ('منسق التدريب', 'منسق التدريب'), ('مستشار طبي', 'مستشار طبي'), ('لوجستي إسعاف', 'لوجستي إسعاف'), ('مسؤول مركز', 'مسؤول مركز'), ('سائق', 'سائق'), ('مستخدم', 'مستخدم')], max_length=50, null=True, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(blank=True, choices=[('Ambulance Team Coordinator', 'Ambulance Team Coordinator'), ('Assistant Ambulance Coordinator', 'Assistant Ambulance Coordinator'), ('Ambulance Operations Coordinator', 'Ambulance Operations Coordinator'), ('Training Coordinator', 'Training Coordinator'), ('Medical Advisor', 'Medical Advisor'), ('Ambulance Logistic', 'Ambulance Logistic'), ('Center Official', 'Center Official'), ('Driver', 'Driver'), ('user', 'user')], max_length=50, null=True, verbose_name='المنصب بالانكليزي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank_in_team',
            field=models.CharField(choices=[('قائد قطاع', 'قائد قطاع'), ('قائد قطاع تحت التدريب', 'قائد قطاع تحت التدريب'), ('قائد فريق', 'قائد فريق'), ('كشاف', 'كشاف'), ('مسعف', 'مسعف'), ('مسعف تحت التدريب', 'مسعف تحت التدريب')], max_length=50, verbose_name='الرتبة ضمن الفريق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sarc_adjective',
            field=models.CharField(choices=[('متطوع', 'متطوع'), ('موظف', 'موظف')], max_length=50, verbose_name='الصفة الهلالية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoulder_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50, verbose_name='قياس الكتفين'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_status',
            field=models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_branch',
            field=models.CharField(choices=[('فرع حماة', 'فرع حماة'), ('شعبة السلمية', 'شعبة السلمية'), ('شعبة السقيلبية', 'شعبة السقيلبية'), ('شعبة مصياف', 'شعبة مصياف')], max_length=50, verbose_name='الشعبة'),
        ),
    ]
