# Generated by Django 3.0.7 on 2020-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200619_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='center',
            field=models.CharField(choices=[('450', '450'), ('480', '480'), ('490', '490')], default='450', max_length=50, verbose_name='المركز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_e',
            field=models.CharField(blank=True, choices=[('Ambulance Team Coordinator', 'Ambulance Team Coordinator'), ('Assistant Ambulance Coordinator', 'Assistant Ambulance Coordinator'), ('Ambulance Operations Coordinator', 'Ambulance Operations Coordinator'), ('Training Coordinator', 'Training Coordinator'), ('Medical Advisor', 'Medical Advisor'), ('Ambulance Logistic', 'Ambulance Logistic'), ('Center Official', 'Center Official'), ('Driver', 'Driver'), ('User', 'User')], max_length=50, null=True, verbose_name='المنصب بالانكليزي'),
        ),
    ]
