# Generated by Django 3.0.7 on 2020-06-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='brith_date',
            new_name='birth_date',
        ),
    ]
