# Generated by Django 3.0.7 on 2020-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200620_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cources', models.CharField(max_length=50, verbose_name='اسم الدورة')),
            ],
            options={
                'verbose_name': 'Cources',
                'verbose_name_plural': 'Courcess',
            },
        ),
    ]
