# Generated by Django 3.0.7 on 2020-06-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_cources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_date', models.DateField(verbose_name='تاريخ الدورة')),
                ('cource_place', models.CharField(max_length=50, verbose_name='مكان الدورة')),
                ('cource_day', models.IntegerField(verbose_name='عدد أيام الدورة')),
                ('adj', models.CharField(choices=[('منسق دورة', 'منسق دورة'), ('مدرب', 'مدرب'), ('متدرب', 'متدرب'), ('لوجستي', 'لوجستي')], max_length=50, verbose_name='صفة المشاركة ')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Cources', verbose_name='الدورة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Cource',
                'verbose_name_plural': 'Cources',
            },
        ),
    ]
